Resources:
  ContractsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
        - "AttributeName": "playerId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
        - "AttributeName": "playerId"
          "KeyType": "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "Contracts"

