Resources:
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
        - "AttributeName": "name"
          "AttributeType": "N"
        - "AttributeName": "battingAverage"
          "AttributeType": "N"
        - "AttributeName": "earnedRunsAverage"
          "AttributeType": "N"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "Players"
      GlobalSecondaryIndexes:
        - IndexName: "BattingAverageIndex"
          KeySchema:
            - AttributeName: "battingAverage"
              KeyType: "HASH"
            - AttributeName: "name"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "hits"
              - "atBats"
        - IndexName: "ERAIndex"
          KeySchema:
            - AttributeName: "earnedRunsAverage"
              KeyType: "HASH"
            - AttributeName: "name"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "inningsPitched"
              - "runsAllowed"
